name: Build
on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer Cython==0.29.33 virtualenv
        pip install git+https://github.com/kivy/python-for-android.git
        
    - name: Setup python-for-android
      run: |
        mkdir -p /home/runner/.buildozer/android/platform
        git clone https://github.com/kivy/python-for-android.git /home/runner/.buildozer/android/platform/python-for-android
        cd /home/runner/.buildozer/android/platform/python-for-android
        python setup.py install

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: '9477386'  # 최신 버전 사용
        
    - name: Install Android SDK platform tools
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
      env:
        JAVA_HOME: ${{ env.JAVA_HOME_11_X64 }}

    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        
    - name: Build with Buildozer
      run: |
        sudo mkdir -p /home/runner/.buildozer
        sudo chown -R $USER:$USER /home/runner/.buildozer
        export PATH=$PATH:/home/runner/.local/bin
        buildozer android debug
      env:
        BUILDOZER_WARN_ON_ROOT: 0
        JAVA_HOME: ${{ env.JAVA_HOME_11_X64 }}
        ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/25.2.9519653
        ANDROID_HOME: /usr/local/lib/android/sdk

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: bin/*.apk
