   name: Build
   on: [push, pull_request]

   jobs:
     build-android:
       name: Build for Android
       runs-on: ubuntu-latest

       steps:
         - name: Checkout
           uses: actions/checkout@v2

         - name: Build with Buildozer
           uses: ArtemSBulgakov/buildozer-action@v1
           id: buildozer
           with:
             workdir: .
             buildozer_version: stable
             command: buildozer android debug
           env: BUILDOZER_WARN_ON_ROOT: 0
           
         - name: Upload artifacts
           uses: actions/upload-artifact@v3
           with:
             name: package
             path: ${{ steps.buildozer.outputs.filename }}
