name: Build
on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer Cython==0.29.33 virtualenv

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: .buildozer_global
        key: ${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

    - name: Build with Buildozer
      run: |
        buildozer android debug
      env:
        BUILDOZER_WARN_ON_ROOT: 0
        JAVA_HOME: ${{ env.JAVA_HOME_11_X64 }}
        ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/25.2.9519653
        ANDROID_HOME: /usr/local/lib/android/sdk

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: bin/*.apk
