name: Build
on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer
          pip install cython==0.29.19

      - name: Cache Apache Ant
        uses: actions/cache@v2
        id: cache-ant
        with:
          path: apache-ant-1.9.4
          key: ${{ runner.os }}-ant-1.9.4

      - name: Download Apache Ant
        if: steps.cache-ant.outputs.cache-hit != 'true'
        run: |
          wget https://downloads.apache.org/ant/binaries/apache-ant-1.9.4-bin.tar.gz || \
          wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.9.4-bin.tar.gz || \
          wget https://www-eu.apache.org/dist/ant/binaries/apache-ant-1.9.4-bin.tar.gz
          tar -xzf apache-ant-1.9.4-bin.tar.gz

      - name: Set Apache Ant path
        run: echo "ANDROID_ANT_HOME=$PWD/apache-ant-1.9.4" >> $GITHUB_ENV

      - name: Network Diagnostics
        run: |
          nslookup archive.apache.org
          traceroute archive.apache.org
          curl -v https://archive.apache.org

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable
          command: buildozer android debug
        env:
          BUILDOZER_WARN_ON_ROOT: 0

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
