name: Build
on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer
          pip install cython==0.29.19

      - name: Check DNS settings
        run: |
          cat /etc/resolv.conf
          ping -c 4 archive.apache.org

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable
          command: buildozer android debug
        env:
          BUILDOZER_WARN_ON_ROOT: 0
        # 재시도 메커니즘 추가
        continue-on-error: true

      - name: Retry Build on Failure
        if: steps.buildozer.outcome == 'failure'
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: .
          buildozer_version: stable
          command: buildozer android debug
        env:
          BUILDOZER_WARN_ON_ROOT: 0

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
