name: Build
on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install --upgrade buildozer
          pip install --upgrade cython==0.29.19

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          sudo apt-get install -y libltdl-dev libffi-dev libssl-dev autoconf autotools-dev cmake

      - name: Set up Apache Ant
        run: |
          sudo apt-get install -y ant
          echo "ANDROID_ANT_HOME=/usr/share/ant" >> $GITHUB_ENV
          echo "/usr/share/ant/bin" >> $GITHUB_PATH

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: ~/.buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
          

      - name: Build with Buildozer
        run: |
          sudo mkdir -p /github/workspace/.buildozer
          sudo chown -R $USER:$USER /github/workspace/.buildozer
          buildozer android debug
        env:
          BUILDOZER_WARN_ON_ROOT: 0
          JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/27.1.12297006
          ANDROID_HOME: /usr/local/lib/android/sdk

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: bin/*.apk
